name: Merge Fast-Forward

on:
  pull_request:
    types:
      - labeled

jobs:
  merge-ff:
    if: github.event.label.name == 'merge-ff'
    runs-on: ubuntu-latest

    env:
      # secrets.GITHUB_TOKENだと、ブランチ保護ルールを無効化する権限が無いため、PATを利用する
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      # チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # マージの準備
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 保護ルールを無効化 (GitHub API)
      - name: Disable branch protection
        run: |
          base_branch=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")
          head_branch=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          for branch in $base_branch $head_branch; do
            curl -X DELETE \
              -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"required_status_checks":null,"enforce_admins":null,"required_pull_request_reviews":null, "restrictions":null}' \
              https://api.github.com/repos/${{ github.repository }}/branches/$branch/protection
          done

      # リモートブランチをフェッチ
      - name: Fetch all branches
        run: git fetch --all

      # baseブランチに移動して、headブランチをファストフォワードでマージ
      - name: Merge head into base (fast-forward)
        run: |
          base_branch=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")
          head_branch=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          git checkout $base_branch
          git pull origin $base_branch
          git merge --ff-only origin/$head_branch

      # リモートにプッシュ
      - name: Push changes
        run: |
          base_branch=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")
          git remote set-url origin https://github-actions:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin $base_branch

      # 保護ルールを再有効化(GitHub API)
      - name: Re-enable branch protection for base and head
        run: |
          base_branch=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")
          head_branch=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          for branch in $base_branch $head_branch; do
            curl -X PUT \
              -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"required_status_checks": {"strict": true, "contexts": []}, "required_pull_request_reviews":{"required_approving_review_count":0}, "enforce_admins": true, "restrictions":null}' \
              https://api.github.com/repos/${{ github.repository }}/branches/$branch/protection
          done
