name: Merge Fast-Forward

on:
  pull_request:
    types:
      - labeled

jobs:
  merge-ff:
    if: github.event.label.name == 'merge-ff'
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # マージの準備
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 保護ルールを無効化 (GitHub API)
      - name: Disable branch protection
        run: |
          for branch in main develop; do
            curl -X DELETE \
              -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Yuki-Nakamura4/cicd-practice/branches/$branch/protection
          done

      # リモートブランチをフェッチ
      - name: Fetch all branches
        run: git fetch --all

      # mainブランチに移動して、developをファストフォワードでマージ
      - name: Merge develop into main (fast-forward)
        run: |
          git checkout main
          git pull origin main
          git merge --ff-only origin/develop

      # リモートにプッシュ
      - name: Push changes
        run: |
          git remote set-url origin https://github-actions:${{ env.GITHUB_TOKEN }}@github.com/Yuki-Nakamura4/cicd-practice.git
          git push origin main
      # 保護ルールを再有効化 (GitHub API)
      - name: Re-enable branch protection for main and develop
        run: |
          for branch in main develop; do
            curl -X PUT \
              -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              # allow_deletionsと
              -d '{"required_status_checks": {"strict": true, "contexts": []},lock_branch: true,  "enforce_admins": true}' \
              https://api.github.com/repos/Yuki-Nakamura4/cicd-practice/branches/$branch/protection
          done
